# Generated by Django 3.0.8 on 2020-09-17 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tacos_ordered', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tortilla', models.CharField(choices=[('flour', 'Flour'), ('corn', 'Corn')], default='flour', max_length=10)),
                ('taco_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_ordered', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tacos_on_order', to='home.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(choices=[('egg', 'Egg'), ('potato', 'Potato'), ('bean', 'Bean'), ('cheese', 'Cheese'), ('carne asada', 'Carne Asada'), ('chicken fajita', 'Chicken Fajita'), ('beef fajita', 'Beef Fajita'), ('pastor', 'Pastor'), ('barbacoa', 'Barbacoa'), ('lengua', 'Lengua'), ('bacon', 'Nacon'), ('nopales', 'Nopales'), ('sausage', 'Sausage')], max_length=255)),
                ('ingredient_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='home.Taco')),
            ],
        ),
    ]
