# Generated by Django 3.0.8 on 2020-09-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200917_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taco',
            name='order',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tacos_on_order', to='home.Order'),
        ),
    ]
